export default {
  "login": "Samul333",
  "id": 30742012,
  "node_id": "MDQ6VXNlcjMwNzQyMDEy",
  "avatar_url": "https://avatars.githubusercontent.com/u/30742012?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Samul333",
  "html_url": "https://github.com/Samul333",
  "followers_url": "https://api.github.com/users/Samul333/followers",
  "following_url": "https://api.github.com/users/Samul333/following{/other_user}",
  "gists_url": "https://api.github.com/users/Samul333/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Samul333/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Samul333/subscriptions",
  "organizations_url": "https://api.github.com/users/Samul333/orgs",
  "repos_url": "https://api.github.com/users/Samul333/repos",
  "events_url": "https://api.github.com/users/Samul333/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Samul333/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Samul Shrestha",
  "company": null,
  "blog": "",
  "location": "Kathmandu, Nepal",
  "email": null,
  "hireable": null,
  "bio": "How long are you going to wait before you demand the best for yourself?",
  "twitter_username": null,
  "public_repos": 26,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2017-08-05T04:08:11Z",
  "updated_at": "2021-03-27T13:31:25Z"
  }